### ISSUE TITLE
Unbound and props.conf event_cleaner3

### ISSUE THREAD

**Issue by mattcosa** [my2ndhead/TA-pfsense#10]
In the `default/props.conf` under stanza `[pfsense]` there is an index time SEDCMD:

`SEDCMD-event_cleaner3`

This breaks the `[pfsense:unbound]` extraction later in the conf by dropping the Date/Time and application fields from the _raw log.

e.g a log for the following:

`Jul 28 08:32:11 unbound: [1812:1] info: resolving mysite.mysite.com. A IN`

will result in a _raw log of:

`[1812:1] info: resolving mysite.mysite.com. A IN`

The latter stanza `[pfsense:unbound]` is never run, and the `sourcetype` is marked as `pfsense` rather than `pfsense:unbound`. 

Commenting out `SEDCMD-event_cleaner3` results in the _raw being correctly stored, and all field extractions working.

What was `SEDCMD-event_cleaner3` for, and is commenting out the `SEDCMD `the best way to address the `sourcetype `not being correctly assigned?

**Comment by my2ndhead** [comment]
IIRC, the SEDCMDs were added to remove timestamps that are put there by the syslog receiver.

The more correct way to disable the setting is to set it to an empty value under local/props.conf:

```
[pfsense]
SEDCMD-event_cleaner3 =
```

**Comment by mattcosa** [comment]
Thanks for clarifying. I'm using the Splunk UDP input, so that makes sense as I don't have an intermediate SYSLOG.

I'll return the default/props.conf back to source, and make that change in local. 

Cheers.
