### ISSUE TITLE
Sourcetype Break On DNS Resolution

### ISSUE THREAD

**Issue by Apocrathia** [my2ndhead/TA-pfsense#3]
I've been having an issue with this plugin not properly parsing all of the pfsense:\* sourcetypes if I have the input set to resolve the hostname via DNS. All fields only show up as simple 'pfsense' and not 'pfsense:servicename'. If I switch the input to IP resolution, everything works fine. Any ideas?

**Comment by Apocrathia** [comment]
Now all sourcetypes appear as 'pfsense:' regardless of what connection_host is set to.

**Comment by Apocrathia** [comment]
It looks like the last commit to line 2 in your transforms.conf broke it. Reverting fixed everything.
https://github.com/my2ndhead/TA-pfsense/commit/559b9d45345cc546600fa3c7b6a5056177ca29b4
What was the new regex supposed to do?

**Comment by my2ndhead** [comment]
Hi Ian

Currently investigating what has happened.

Mika>

**Comment by my2ndhead** [comment]
Can you try this Regex in transforms.conf? Requires a restart of your
Indexer/Heavy Forwarder)

REGEX = ^\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}\s+(\w+):

Thanks!

Mika>

**Comment by Apocrathia** [comment]
Looks like that works. There's still a few filterlog messages where the action isn't getting extracted correctly, but it looks like it's related to IPV6. That's another issue entirely.

**Comment by my2ndhead** [comment]
Ok. Will push another release...

Regarding IPv6: Just open issues regarding those bugs.

Thanks!
Mika>

**Comment by Apocrathia** [comment]
You're awesome. Thanks!

**Comment by my2ndhead** [comment]
Only when I have the time :-)

Ok. 2.0.5 should be on Splunkbase now.

Thanks
Mika>

**Comment by gsiemon** [comment]
Hi, I've just setup Splunk for the first time and installed TA-pfsense 2.0.5.  I'm having the same issue as the OP.  All events are being recognised as pfsense:.  If I revert the change as per the OP's suggestion then everything works fine.  Did this issue get corrected in the 2.0.5 release?  I haven't tried your suggested fix as the OP said it broke IPv6 stuff.
