### ISSUE TITLE
Code to partially handle unbound DNS

### ISSUE THREAD

**Issue by somm15** [my2ndhead/TA-pfsense#5]
Hi Mika,

I'm not a Splunk expert yet but I added a few lines to more or less handle unbound DNS logs and make them more or less CIM compliant.

Regards,

Simon

---eventtypes.conf --
...
[pfsense_unbound]
search = sourcetype=pfsense:unbound

-- props.conf --
...
[pfsense:unbound]
EXTRACT-queries = info: resolving (?P<query>\S{2,})\s(?P<query_type>\S+)
EXTRACT-response = info: response for (?P<query>\S+)\s(?P<record_type>\S+)
EXTRACT-reply = info: reply from\s(\S+)\s(?P<src>(\d|\.)+)#(?P<src_port>(\d+))

-- tags.conf --
...
[eventtype=pfsense_unbound]
network = enabled
resolution = enabled
dns = enabled

**Comment by anthonysomerset** [comment]
@simongillet i've made some adjustments to your code and created a Pull request for this - confirmed working on PFsense 2.3.4

**Comment by somm15** [comment]
Thanks. 
By the way, I don't know if DHCP stopped for you as well but after upgrade my DHCP logs were not correctly processed anymore.

I made this dirty line to get it working again.

[pfsense:dhcpd]
EXTRACT-ipv4_dhcp = (?<vendor_action>DHCPACK|DHCPREQUEST|DHCPRELEASE|DHCPOFFER|DHCPDISCOVER|DHCPACK|DHCPINFORM) ((?:on|for|of) (?<dest_ip>\S+) (\(\S+\) )?)?(((?:from|to) (?<src_mac>\S+) (\(\S+\) )?))?via (?<src_interface>\S+)

**Comment by anthonysomerset** [comment]
mine seems OK

**Comment by my2ndhead** [comment]
Thanks for the updates. Creating a new release, let me know if you find any bugs.
