### ISSUE TITLE
DHCP extraction - device name

### ISSUE THREAD

**Issue by mbistrom** [my2ndhead/TA-pfsense#9]
May I suggest editing props.conf to include the device name (when available) in the DHCP-logs
Change from
`EXTRACT-ipv4_dhcp = (?<vendor_action>DHCPACK|DHCPREQUEST) (?:on|for) (?<dest_ip>\S+) (?:from|to) (?<src_mac>\S+) \(.*\) via (?<src_interface>\S+)`
to
`EXTRACT-ipv4_dhcp = (?<vendor_action>DHCPACK|DHCPREQUEST) (?:on|for) (?<dest_ip>\S+) (?:from|to) (?<src_mac>\S+)(\s\((?<device_name>.*)\))? via (?<src_interface>\S+)`

**Comment by my2ndhead** [comment]
Fixed with next release
